apiVersion: apps/v1
kind: Deployment
metadata:
  name: k4filler-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k4filler-backend
  template:
    metadata:
      labels:
        app: k4filler-backend
    spec:
      containers:
      - name: backend
        image: gcr.io/k4-filler-service-2024/k4filler-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: k4filler-secrets
              key: anthropic-api-key 