apiVersion: apps/v1
kind: Deployment
metadata:
  name: k4filler-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k4filler-frontend
  template:
    metadata:
      labels:
        app: k4filler-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/k4-filler-service-2024/k4filler-frontend:latest
        ports:
        - containerPort: 3000